AWSTemplateFormatVersion: '2010-09-09'
Description: Example using Cloudformation companion

Parameters:
  Lambda:
    Description: ARN of the backend lambda function for the custom resource
    Type: String

Resources:
  Companion:
    Type: AWS::CloudFormation::CustomResource
    Version: "1.0"
    Properties:
      ServiceToken: !Ref Lambda
      Cloudformation:
        - StackName: '<your_stack>'
          Resources: [ '<resource_from_stack>' ]
          Outputs: [ '<output_from_stack>' ]

Outputs:
  Output:
    Value:
      Fn::GetAtt:
        - "Companion"
        - "Cloudformation::<your_stack>::Outputs::<output_from_stack>"
  Resource:
    Value:
      Fn::GetAtt:
        - "Companion"
        - "Cloudformation::<your_stack>::Resources::<resource_from_stack>"
